# Template sync: downstream repos and paths to sync.
# - repositories: exact repo names or glob patterns; patterns resolved via gh repo list.
# - include_paths: default allowlist for all repos (only these files). If empty, exclude_paths is used as blacklist.
# - repo_include_paths: optional per-repo overrides. Repos listed here use their list instead of include_paths.

repositories:
  - template-1-terraform
  - template-cursor
  - terraform-github

include_paths:
  - .github/workflows/dependabot-automerge.yaml
  - .github/workflows/pre-commit-update.yaml
  - .github/workflows/pre-commit.yaml

repo_include_paths:
  template-1-terraform:
    - .github/workflows/sync.yaml
    - .github/scripts/*
  template-cursor:
    - .github/workflows/sync.yaml
    - .github/scripts/*

exclude_paths: []
